# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{wkhtmltopdf-daemon}
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Stefan Manneck"]
  s.date = %q{2010-08-18}
  s.default_executable = %q{wkhtmltopdf-daemon}
  s.description = %q{convert a given URL to an pdf file with the wkhtmltopdf tool}
  s.email = %q{smanneck@sub-link.de}
  s.executables = ["wkhtmltopdf-daemon"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "bin/wkhtmltopdf-daemon",
     "lib/...",
     "lib/wkhtmltopdf-daemon.rb",
     "lib/wkhtmltopdf-daemon/config.ru",
     "test/helper.rb",
     "test/test_wkhtmltopdf-daemon.rb",
     "wkhtmltopdf-daemon.gemspec"
  ]
  s.homepage = %q{http://github.com/bule/wkhtmltopdf-daemon}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{convert html to pdf}
  s.test_files = [
    "test/helper.rb",
     "test/test_wkhtmltopdf-daemon.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    else
      s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    end
  else
    s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
  end
end

